### ISSUE TITLE
Google Artsdata Preview Add-on loading for non artsdata.ca links

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-google-workspace-smart-chip#1]
When I have a link from github like https://github.com/culturecreates/artsdata-api/issues/11 in Google Docs then I get a Google Smart Chip loading. Only urls that start with `https://kg.artsdata.ca/resource` should trigger the Google Smart Chip.

![Image](https://github.com/culturecreates/artsdata-google-workspace-smart-chip/assets/419491/5f431eab-046b-47b6-aa4f-d2439fad0af1)

**Comment by dev-aravind** [comment]
@saumier This is fixed in the google sheet now.

**Comment by saumier** [comment]
@dev What is matchedUrl method in preview.js?  Is it your code or an App script code.

**Comment by dev-aravind** [comment]
@saumier That is a predefined function to get the url that is matched using the linkPreviewTrigger.
