### ISSUE TITLE
Event URL loaded in place of image URL

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/artsdata-google-workspace-smart-chip#10]
Upon minting an ID from an event loaded from the smart chip prototype, I realized the Event URL was stated as a value for `image`. The problem is not an outcome of the minting process; is present in the source data:
http://indigenous-performances/row/temporary/d7daa455bc3a4879a1f8db9c257d3baa

The `image` property should be automatically populated when no data is available.

**Comment by saumier** [comment]
This is fixed.

The spreadsheet MUST have a column named `Image` which should contain urls for the images or blank if there is no image.

I renamed "Image URL" to "Image" in @GaryMan1968 spreadsheet https://docs.google.com/spreadsheets/d/1dsaWJIEmcPmcbbXpEYPfgvPNSA60vEfpK1t1mxQjwiA/edit?gid=0#gid=0

I also ran the import so the data is now loaded into Artsdata with the images listed in the spreadsheet.
